### ISSUE TITLE
incorrect implementation (?) of NACC algorithm in "constitutive_models.cuh"

### ISSUE THREAD

**Issue by igorg520b** [penn-graphics-research/claymore#10]
In the function "compute_stress<float, MaterialE::NACC>" that updates the deformation gradient there is the variable "s_hat_trial_sqrnorm" that stands for the squared norm of the matrix s_hat. However, in the paper "CD-MPM: Continuum Damage Material Point Methods for Dynamic Fracture Animation: Supplemental Document", just the norm is used, not the squared norm.

**Comment by Destranix** [comment]
Even with that change NACC seems to be instable on my system on contact. Guess it doesn't make much sense to apply that change till NACC is in a working state.

**Comment by igorg520b** [comment]
Ok, thanks for looking into this. Makes me wonder how they computed the examples from the paper!
