### ISSUE TITLE
Error: ""Assertion failed: IsObject(), file D:\claymore\build\_deps\rapidjson-src\include\rapidjson/document.h, line 1274" while running GMPM

### ISSUE THREAD

**Issue by lokitkhemka** [penn-graphics-research/claymore#11]
When I am running the GMPM executable with input files "knot1.poly" or "dragon_particles.bin", I keep getting error as mentioned in the title.

Any help is appreciated. Thank you.

**Comment by Destranix** [comment]
Your input file must be a valid json scene file. Like the one present in the GMPM scenes folder (which is copied on install into the binary folder for easier access).
Also currently only SDF-Files are supported as input.

**Comment by lokitkhemka** [comment]
Yes, it works. Thanks a lot.
